package com.saptool.ui.executionlab;


import com.saptool.ui.Init;
import com.saptool.ui.UI_Design;
import com.saptool.utils.Generic;
import com.saptool.utils.GlobalConstants;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;

/**
 *
 * @author Bharath Kumar Reddy Vatrapu
 */
public class Controls_old extends javax.swing.JPanel {
    HashMap<String,String> testngProjectParams=new HashMap<String,String>();
    public Generic generic = new Generic();
    /**
     * Creates new form Controls
     */
    public Controls_old() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnLeft = new javax.swing.JButton();
        btnRunAll = new javax.swing.JButton();
        btnRunSelected = new javax.swing.JButton();
        btnAddQueue = new javax.swing.JButton();
        btnCreateSuite = new javax.swing.JButton();
        btnStopExecutions = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnLeft.setBackground(new java.awt.Color(255, 255, 255));
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ExecutionLab/Sort_Left_100px_1.png")));
        btnLeft.setBorder(null);
        btnLeft.setFocusPainted(false);
        btnLeft.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRunAll.setBackground(new java.awt.Color(204, 204, 255));
        btnRunAll.setFont(new java.awt.Font("Tahoma", 1, 20));
        btnRunAll.setText("Run All");
        btnRunAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunAllActionPerformed(evt);
            }
        });

        btnRunSelected.setBackground(new java.awt.Color(204, 204, 255));
        btnRunSelected.setFont(new java.awt.Font("Tahoma", 1, 20));
        btnRunSelected.setText("Run Selected");
        btnRunSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunSelectedActionPerformed(evt);
            }
        });

        btnAddQueue.setBackground(new java.awt.Color(204, 204, 255));
        btnAddQueue.setFont(new java.awt.Font("Tahoma", 1, 20));
        btnAddQueue.setText("Add Queue");
        btnAddQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQueueActionPerformed(evt);
            }
        });

        btnCreateSuite.setBackground(new java.awt.Color(204, 204, 255));
        btnCreateSuite.setFont(new java.awt.Font("Tahoma", 1, 20));
        btnCreateSuite.setText("Create Suite");
        btnCreateSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSuiteActionPerformed(evt);
            }
        });

        btnStopExecutions.setBackground(new java.awt.Color(204, 204, 255));
        btnStopExecutions.setFont(new java.awt.Font("Tahoma", 1, 20));
        btnStopExecutions.setText("Stop Executions");
        btnStopExecutions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopExecutionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnRunSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(btnRunAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCreateSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(btnAddQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addComponent(btnStopExecutions, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnRunSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnAddQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnCreateSuite, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                                        .addComponent(btnRunAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnStopExecutions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(55, Short.MAX_VALUE))
        );
    }
        private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {
            ExecutionLab.setpanelNotVisible();
            ExecutionLab.testNgParams.setVisible(true);
        }
    private void btnRunAllActionPerformed(java.awt.event.ActionEvent evt) {
        if(GlobalConstants.NODE_STATUS){

        } else {
            if(!GlobalConstants.HUB_STATUS){
                generic.startHub();
            }
            generic.startNode();
        }

        // TODO add your handling code here:
        int rowCount=ExecutionLab.tblTestSripts.getModel().getRowCount();
        try {
            GlobalConstants.DATE_TIME = Generic.getTime() + "_" + Generic.getDate();
            GlobalConstants.EXECUTION_PROJECT = GlobalConstants.EXECUTIONS_FOLDER_PATH + File.separator + GlobalConstants.DATE_TIME;

            String srcDir  = GlobalConstants.SELECTED_PROJECT_PATH;
            String destDir = GlobalConstants.EXECUTION_PROJECT;
            Generic.copyDirectory(new File(srcDir),new File(destDir));

            Path source = Paths.get(GlobalConstants.CONFIG_TEMP_FOLDER_PATH + File.separator + "Temp_Exec_TestNG.xml");
            Path newdir = Paths.get(GlobalConstants.EXECUTION_PROJECT+File.separator+GlobalConstants.TEST_FRAMEWORK_TESTEXECUTION_FOLDER );


            Files.copy(source, newdir.resolve("Temp_Exec_TestNG.xml"), REPLACE_EXISTING);
//            Generic.copyDirectory(new File(source));
            String readPage = Generic.readText(GlobalConstants.EXECUTION_PROJECT+File.separator+GlobalConstants.TEST_FRAMEWORK_TESTEXECUTION_FOLDER+File.separator+"Temp_Exec_TestNG.xml");

            String className = null;
            String tblScript = null;
            for (int count = 0; count < rowCount; count++){
                tblScript=ExecutionLab.tblTestSripts.getModel().getValueAt(count, 1).toString();
                tblScript=tblScript.replaceAll(".java","");

                className = "<class name=\"com.testProject.testSuites."+GlobalConstants.SELECTED_EXEC_NODE_MODULE+"."+tblScript+"\" />";
                readPage = readPage.replace("</classes>",className+System.lineSeparator()+"</classes>");

            }
            String suite_report_name=null;
            suite_report_name=GlobalConstants.SELECTED_EXEC_NODE_MODULE+"_"+Init.testBrowser;
            readPage=readPage.replace("Temp",suite_report_name);

            Generic.writeText(readPage,GlobalConstants.EXECUTION_PROJECT+File.separator+GlobalConstants.TEST_FRAMEWORK_TESTEXECUTION_FOLDER+File.separator+"Temp_Exec_TestNG.xml",false);


            Init.testNGFile = "Temp_Exec_TestNG";
            Init.TestNG_Params.put("browser", Init.testBrowser);
            Init.TestNG_Params.put("suitefile", Init.testNGFile);
            Init.TestNG_Params.put("platform", Init.testPlatform);
            String banner=null;
            testngProjectParams = Init.readParams_PropHash();
            for (Map.Entry<String, String> entry : testngProjectParams.entrySet()) {
                Init.TestNG_Params.put(entry.getKey(), entry.getValue());
                banner = entry.getValue();
            }
            GlobalConstants.EXECUTION_NAME = Init.testPlatform.toUpperCase()+"_"+Init.testBrowser.toUpperCase()+"_"+GlobalConstants.SELECTED_EXEC_NODE_MODULE.toUpperCase()+banner.toUpperCase();


            RunExecutor runExecutor =  new RunExecutor();

            runExecutor.setVisible(true);
            runExecutor.txtExecName.setText(GlobalConstants.EXECUTION_NAME);
            runExecutor.Run();
        }catch (Exception e){
            e.printStackTrace();
        }

    }

    private void btnRunSelectedActionPerformed(java.awt.event.ActionEvent evt) {
        if(GlobalConstants.NODE_STATUS){

        } else {
            if(!GlobalConstants.HUB_STATUS){
                generic.startHub();
            }
            generic.startNode();
        }
        try {
            GlobalConstants.DATE_TIME = Generic.getTime() + "_" + Generic.getDate();
            GlobalConstants.EXECUTION_PROJECT = GlobalConstants.EXECUTIONS_FOLDER_PATH + File.separator + GlobalConstants.DATE_TIME;

            String srcDir  = GlobalConstants.SELECTED_PROJECT_PATH;
            String destDir = GlobalConstants.EXECUTION_PROJECT;
            Generic.copyDirectory(new File(srcDir),new File(destDir));

            Path source = Paths.get(GlobalConstants.CONFIG_TEMP_FOLDER_PATH + File.separator + "Temp_Exec_TestNG.xml");
            Path newdir = Paths.get(GlobalConstants.EXECUTION_PROJECT+File.separator+GlobalConstants.TEST_FRAMEWORK_TESTEXECUTION_FOLDER );


            Files.copy(source, newdir.resolve("Temp_Exec_TestNG.xml"), REPLACE_EXISTING);
//            Generic.copyDirectory(new File(source));
            String readPage = Generic.readText(GlobalConstants.EXECUTION_PROJECT+File.separator+GlobalConstants.TEST_FRAMEWORK_TESTEXECUTION_FOLDER+File.separator+"Temp_Exec_TestNG.xml");

            String className = null;
            String tblScript = null;

            if (ExecutionLab.tblTestSripts.getSelectedRows().length > -1) {
                int[] selectedrows = ExecutionLab.tblTestSripts.getSelectedRows();
                for (int i = 0; i < selectedrows.length; i++) {
                    tblScript=ExecutionLab.tblTestSripts.getValueAt(selectedrows[i], 1).toString();
                    tblScript=tblScript.replaceAll(".java","");

                    className = "<class name=\"com.testProject.testSuites."+GlobalConstants.SELECTED_EXEC_NODE_MODULE+"."+tblScript+"\" />";
                    readPage = readPage.replace("</classes>",className+System.lineSeparator()+"</classes>");
                }
            }


            String suite_report_name=null;
            suite_report_name=GlobalConstants.SELECTED_EXEC_NODE_MODULE+"_"+Init.testBrowser;
            readPage=readPage.replace("Temp",suite_report_name);

            Generic.writeText(readPage,GlobalConstants.EXECUTION_PROJECT+File.separator+GlobalConstants.TEST_FRAMEWORK_TESTEXECUTION_FOLDER+File.separator+"Temp_Exec_TestNG.xml",false);


            Init.testNGFile = "Temp_Exec_TestNG";
            Init.TestNG_Params.put("browser", Init.testBrowser);
            Init.TestNG_Params.put("suitefile", Init.testNGFile);
            Init.TestNG_Params.put("platform", Init.testPlatform);
            String banner=null;
            testngProjectParams = Init.readParams_PropHash();
            for (Map.Entry<String, String> entry : testngProjectParams.entrySet()) {
                Init.TestNG_Params.put(entry.getKey(), entry.getValue());
                banner = entry.getValue();
            }
            GlobalConstants.EXECUTION_NAME = Init.testPlatform.toUpperCase()+"_"+Init.testBrowser.toUpperCase()+"_"+GlobalConstants.SELECTED_EXEC_NODE_MODULE.toUpperCase()+banner.toUpperCase();


            RunExecutor runExecutor =  new RunExecutor();

            runExecutor.setVisible(true);
            runExecutor.txtExecName.setText(GlobalConstants.EXECUTION_NAME);
            runExecutor.Run();
        }catch (Exception e){
            e.printStackTrace();
        }

    }

    private void btnAddQueueActionPerformed(java.awt.event.ActionEvent evt) {
        String tblScript = null;
        String tbScripts = null;
        String script = null;
        if (ExecutionLab.tblTestSripts.getSelectedRows().length > -1) {
            int[] selectedrows = ExecutionLab.tblTestSripts.getSelectedRows();
            script=ExecutionLab.tblTestSripts.getValueAt(selectedrows[0], 1).toString();
            script=script.replaceAll(".java","");
            for (int i = 1; i < selectedrows.length; i++) {
                tblScript=ExecutionLab.tblTestSripts.getValueAt(selectedrows[i], 1).toString();
                tblScript=tblScript.replaceAll(".java","");
                tbScripts = tbScripts+"@@@@@"+tblScript;
            }
        }
        tbScripts = tbScripts.replaceAll("null",script);

    }

    private void btnCreateSuiteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    private void btnStopExecutionsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddQueue;
    private javax.swing.JButton btnCreateSuite;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRunAll;
    private javax.swing.JButton btnRunSelected;
    private javax.swing.JButton btnStopExecutions;
    // End of variables declaration
}
