package com.saptool.ui.executionlab;


import com.saptool.ui.Init;

import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author Bharath Kumar Reddy Vatrapu
 */
public class TestNgParams_EL extends JPanel {

    /**
     * Creates new form TestNgParams_EL
     */
    public TestNgParams_EL() {
        initComponents();
        btnConfigParam.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        listparams = new JList<>();
        btnRight = new JButton();
        btnLeft = new JButton();
        btnConfigParam = new JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        listparams.setBorder(BorderFactory.createTitledBorder(null, "TestNG Params", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        listparams.setFont(new java.awt.Font("Tahoma", 0, 24));
        listparams.setForeground(new java.awt.Color(0, 51, 204));
//        listparams.setModel(new javax.swing.AbstractListModel<String>() {
////            String[] strings = { "ITEM1", "ITEM2", "ITEM3" };
////            public int getSize() { return strings.length; }
////            public String getElementAt(int i) { return strings[i]; }
////        });
        listparams.addMouseListener(mouseListener);
        jScrollPane1.setViewportView(listparams);

        btnRight.setBackground(new java.awt.Color(255, 255, 255));
        btnRight.setIcon(new ImageIcon(getClass().getResource("/icons/ExecutionLab/Sort_Right_100px.png")));
        btnRight.setBorder(null);
        btnRight.setFocusPainted(false);
        btnRight.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnLeft.setBackground(new java.awt.Color(255, 255, 255));
        btnLeft.setIcon(new ImageIcon(getClass().getResource("/icons/ExecutionLab/Sort_Left_100px_1.png")));
        btnLeft.setBorder(null);
        btnLeft.setFocusPainted(false);
        btnLeft.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnConfigParam.setBackground(new java.awt.Color(255, 255, 255));
        btnConfigParam.setFont(new java.awt.Font("Tahoma", 1, 16));
        btnConfigParam.setForeground(new java.awt.Color(51, 0, 153));
        btnConfigParam.setText("Config Param");
        btnConfigParam.setFocusPainted(false);
        btnConfigParam.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnConfigParamActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLeft, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 427, GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnConfigParam, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                                .addComponent(btnRight, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnConfigParam, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(89, 89, 89)
                                                        .addComponent(btnRight, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(86, 86, 86)
                                                        .addComponent(btnLeft, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
    }

    public static void init_Load(){
        Init.readParams_Prop();
        listparams.setModel(Init.paramNameandValuesListModel);
    }
    private void btnRightActionPerformed(ActionEvent evt) {
        ExecutionLab.setpanelNotVisible();
        ExecutionLab.controls.setVisible(true);
    }

    private void btnLeftActionPerformed(ActionEvent evt) {
        ExecutionLab.setpanelNotVisible();
        ExecutionLab.browsers.setVisible(true);
    }
    MouseListener mouseListener = new MouseAdapter() {
        public void mouseClicked(MouseEvent mouseEvent) {
            if(listparams.getSelectedValue()==null){
                JOptionPane.showMessageDialog(null, "Select parameter", "Warning " , JOptionPane.INFORMATION_MESSAGE);
            } else {
                Init.param_Selected = listparams.getSelectedValue();
                if (Init.param_Selected.contains("=")) {
                    String[] param = Init.param_Selected.split("=");
                    Init.param_Name = param[0];
                } else {
                    Init.param_Name = listparams.getSelectedValue();
                }

                AddValue addValue = new AddValue();
                addValue.setVisible(true);
                AddValue.initLoad();

            }
        }
    };

    private void btnConfigParamActionPerformed(ActionEvent evt) {
        SetupParams setupParams = new SetupParams();
        setupParams.setVisible(true);

    }
    // Variables declaration - do not modify
    private JButton btnConfigParam;
    public static JButton btnLeft;
    private JButton btnRight;
    private JScrollPane jScrollPane1;
    public static JList<String> listparams;
    // End of variables declaration
}
